import { Injectable, Optional } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { ProviderStatus,ProviderHealthStatus,ProviderQuotaStatus,ProviderCredentialRequirement,providerSupportsCapability,type ProviderDeclaration,type ProviderRoutingRequest,type ProviderRoutingResponse,type ProviderScoreComponents,type RoutingCandidate,type RoutingRejectionReason,EligibilityPhase,DEFAULT_ROUTING_SCORE_WEIGHTS,ROUTING_POLICY_VERSION,ROUTING_REJECTION_MESSAGES } from '@vito/contracts';
import { ProviderReadinessProbeService } from './provider-readiness-probe.service';
import { ProviderRuntimeStateService } from './provider-runtime-state.service';

@Injectable()
export class ProviderRouterService {
  constructor(private readonly prisma:PrismaService,private readonly auditService:AuditService,@Optional() private readonly runtimeState?:ProviderRuntimeStateService,@Optional() private readonly readinessProbe?:ProviderReadinessProbeService){}
  async route(request:ProviderRoutingRequest):Promise<ProviderRoutingResponse>{return this.routeInternal(request,Object.freeze([]));}
  async routeForExecution(request:ProviderRoutingRequest):Promise<ProviderRoutingResponse>{const candidates=await this.loadCandidates(request.organizationId);const runtimeRefreshedProviderIds=await this.refreshStaleCandidates(candidates,request);return this.routeInternal(request,runtimeRefreshedProviderIds);}
  private async routeInternal(request:ProviderRoutingRequest,runtimeRefreshedProviderIds:readonly string[]):Promise<ProviderRoutingResponse>{
    const candidates=await this.loadCandidates(request.organizationId);const evaluated=candidates.map(c=>this.evaluateCandidate(c,request));const eligible=evaluated.filter(c=>c.eligible);const rejected=evaluated.filter(c=>!c.eligible);const rejectionReasons:Record<string,RoutingRejectionReason>={};const rejectionPhases:Record<string,EligibilityPhase>={};for(const r of rejected){if(r.rejectionReason)rejectionReasons[r.provider.id]=r.rejectionReason;if(r.rejectionPhase)rejectionPhases[r.provider.id]=r.rejectionPhase;}
    const scored=eligible.map(c=>({...c,scoreComponents:this.computeScore(c.provider),finalScore:0}));for(const s of scored){if(s.scoreComponents)s.finalScore=this.aggregateScore(s.scoreComponents);}scored.sort((a,b)=>{const d=(b.finalScore??0)-(a.finalScore??0);return d!==0?d:a.provider.providerCode.localeCompare(b.provider.providerCode);});const scoredMap=new Map(scored.map(s=>[s.provider.id,s]));const allCandidates=evaluated.map(c=>scoredMap.get(c.provider.id)??c);const selected=scored.length>0?scored[0]:null;
    const scoreComponentsMap:Record<string,ProviderScoreComponents>={};const finalScoresMap:Record<string,number>={};const eligibleCandidateIds:string[]=[];const allCandidateIds:string[]=[];for(const c of allCandidates){allCandidateIds.push(c.provider.id);if(c.eligible)eligibleCandidateIds.push(c.provider.id);if(c.scoreComponents)scoreComponentsMap[c.provider.id]=c.scoreComponents;if(c.finalScore!==undefined)finalScoresMap[c.provider.id]=c.finalScore;}
    const decisionReason=selected?`Provider ${selected.provider.providerCode} ausgewählt (Score: ${selected.finalScore?.toFixed(4)??'N/A'})`:ROUTING_REJECTION_MESSAGES.NO_ELIGIBLE_PROVIDER;
    const decision=await this.prisma.providerRoutingDecision.create({data:{organizationId:request.organizationId,correlationId:request.correlationId,workflowRunId:request.workflowRunId??null,workflowStepRunId:request.workflowStepRunId??null,requestedCapability:request.capability,assuranceLevel:request.assuranceLevel??null,selectedProviderId:selected?.provider.id??null,candidateProviderIds:allCandidateIds as Prisma.InputJsonValue,rejectionReasons:rejectionReasons as Prisma.InputJsonValue,scoreComponents:scoreComponentsMap as unknown as Prisma.InputJsonValue,finalScore:selected?.finalScore??null,decisionReason,routingPolicyVersion:ROUTING_POLICY_VERSION}});
    await this.auditService.record({organizationId:request.organizationId,actorType:'SYSTEM',action:selected?'PROVIDER_SELECTED':'PROVIDER_ROUTING_REQUESTED',entityType:'ProviderRoutingDecision',entityId:decision.id,metadata:{correlationId:request.correlationId,capability:request.capability,assuranceLevel:request.assuranceLevel,selectedProviderId:selected?.provider.id??null,selectedProviderCode:selected?.provider.providerCode??null,candidateCount:allCandidateIds.length,eligibleCount:eligibleCandidateIds.length,rejectionReasons,decisionReason,runtimeRefreshedProviderIds}});
    return{selectedProvider:selected?.provider??null,routingDecisionId:decision.id,eligibleCandidateIds,allCandidateIds,rejectionReasons,rejectionPhases,scoreComponents:scoreComponentsMap,finalScores:finalScoresMap,decisionReason,runtimeRefreshedProviderIds};
  }
  private async refreshStaleCandidates(candidates:readonly ProviderDeclaration[],request:ProviderRoutingRequest):Promise<readonly string[]>{if(!this.runtimeState||!this.readinessProbe)return Object.freeze([]);const refreshed:string[]=[];for(const provider of candidates){if(provider.status!==ProviderStatus.ACTIVE||!providerSupportsCapability(provider,request.capability)||!this.runtimeState.needsRefresh(provider))continue;const result=await this.readinessProbe.refreshIfStale({organizationId:request.organizationId,workflowRunId:request.workflowRunId,workflowStepRunId:request.workflowStepRunId,provider});if(result.refreshed)refreshed.push(provider.id);}return Object.freeze(refreshed);}
  private async loadCandidates(organizationId:string):Promise<ProviderDeclaration[]>{const rows=await this.prisma.agentProvider.findMany({where:{organizationId},orderBy:{providerCode:'asc'},include:{capabilities:true}});return rows.map(r=>({id:r.id,organizationId:r.organizationId,providerCode:r.providerCode,displayName:r.displayName,providerType:r.providerType as any,status:r.status as any,modelFamily:r.modelFamily??undefined,modelName:r.modelName??undefined,modelCode:r.modelCode??undefined,supportedCapabilities:(r.supportedCapabilities as string[])??[],capabilityAssignments:(r.capabilities??[]).map(c=>({capabilityCode:c.capabilityCode,isEnabled:c.isEnabled})),estimatedCostMinorUnits:r.estimatedCostMinorUnits??undefined,healthStatus:r.healthStatus as any,healthCheckedAt:r.healthCheckedAt??undefined,quotaStatus:r.quotaStatus as any,quotaCheckedAt:r.quotaCheckedAt??undefined,qualityScore:r.qualityScore??undefined,latencyScore:r.latencyScore??undefined,costScore:r.costScore??undefined,costMetadata:(r.costMetadata as Record<string,unknown>)??{},assuranceLevels:(r.assuranceLevels as string[])??[],metadata:(r.metadata as Record<string,unknown>)??{},createdAt:r.createdAt,updatedAt:r.updatedAt,credentialRequirement:r.credentialRequirement as ProviderCredentialRequirement}));}
  private evaluateCandidate(provider:ProviderDeclaration,request:ProviderRoutingRequest):RoutingCandidate{if(!providerSupportsCapability(provider,request.capability))return this.rejected(provider,'CAPABILITY_UNSUPPORTED',EligibilityPhase.CAPABILITY);if(provider.status===ProviderStatus.DISABLED)return this.rejected(provider,'PROVIDER_DISABLED',EligibilityPhase.STATUS_POLICY);if(provider.status===ProviderStatus.DEGRADED)return this.rejected(provider,'PROVIDER_UNHEALTHY',EligibilityPhase.STATUS_POLICY);if(this.runtimeState&&!this.runtimeState.isHealthFresh(provider))return this.rejected(provider,'HEALTH_STATUS_STALE',EligibilityPhase.AVAILABILITY);if(provider.healthStatus===ProviderHealthStatus.DISABLED)return this.rejected(provider,'PROVIDER_DISABLED',EligibilityPhase.AVAILABILITY);if(provider.healthStatus===ProviderHealthStatus.UNAVAILABLE)return this.rejected(provider,'PROVIDER_UNAVAILABLE',EligibilityPhase.AVAILABILITY);if(provider.healthStatus===ProviderHealthStatus.QUOTA_LIMITED)return this.rejected(provider,'QUOTA_UNAVAILABLE',EligibilityPhase.AVAILABILITY);if(provider.healthStatus===ProviderHealthStatus.UNKNOWN)return this.rejected(provider,'PROVIDER_UNHEALTHY',EligibilityPhase.AVAILABILITY);if(this.runtimeState&&!this.runtimeState.isQuotaFresh(provider))return this.rejected(provider,'QUOTA_STATUS_STALE',EligibilityPhase.QUOTA);if(provider.quotaStatus===ProviderQuotaStatus.EXHAUSTED)return this.rejected(provider,'QUOTA_EXHAUSTED',EligibilityPhase.QUOTA);if(provider.quotaStatus===ProviderQuotaStatus.UNKNOWN)return this.rejected(provider,'QUOTA_STATUS_UNKNOWN',EligibilityPhase.QUOTA);if(request.assuranceLevel&&provider.assuranceLevels.length>0&&!provider.assuranceLevels.includes(request.assuranceLevel))return this.rejected(provider,'ASSURANCE_LEVEL_UNSUPPORTED',EligibilityPhase.ASSURANCE);if(request.independenceContext){const violation=this.checkIndependence(provider,request.independenceContext);if(violation)return this.rejected(provider,violation,EligibilityPhase.INDEPENDENCE);}const max=request.budget?.maxCostMinorUnits;if(max!==undefined){const cost=provider.estimatedCostMinorUnits;if(cost===undefined||cost===null)return this.rejected(provider,'COST_UNKNOWN',EligibilityPhase.BUDGET);if(cost>max)return this.rejected(provider,'BUDGET_INCOMPATIBLE',EligibilityPhase.BUDGET);}return{provider,eligible:true};}
  private checkIndependence(provider:ProviderDeclaration,ctx:any):RoutingRejectionReason|null{if(ctx.builderProviderId&&provider.id===ctx.builderProviderId)return'INDEPENDENCE_REQUIREMENT_UNSATISFIED';if(ctx.builderModelFamily&&provider.modelFamily&&provider.modelFamily===ctx.builderModelFamily)return'INDEPENDENCE_REQUIREMENT_UNSATISFIED';if(ctx.previousReviewerProviderIds.includes(provider.id))return'INDEPENDENCE_REQUIREMENT_UNSATISFIED';if(provider.modelFamily&&ctx.previousReviewerModelFamilies.includes(provider.modelFamily))return'INDEPENDENCE_REQUIREMENT_UNSATISFIED';if(!provider.modelFamily||provider.modelFamily.trim()==='')return'MODEL_IDENTITY_UNVERIFIABLE';return null;}
  private computeScore(provider:ProviderDeclaration):ProviderScoreComponents{const quality=provider.qualityScore??0.5;const cost=provider.costScore!==undefined?Math.max(0,1-provider.costScore/1000):0.5;const latency=provider.latencyScore!==undefined?Math.max(0,1-provider.latencyScore/10000):0.5;const healthPreference=provider.healthStatus===ProviderHealthStatus.HEALTHY?1:provider.healthStatus===ProviderHealthStatus.DEGRADED?0.5:0.3;return{qualityScore:quality,costScore:cost,latencyScore:latency,healthPreference,raw:{qualityRaw:provider.qualityScore??0.5,costRaw:provider.costScore??500,latencyRaw:provider.latencyScore??5000,healthRaw:healthPreference}};}
  private aggregateScore(c:ProviderScoreComponents):number{const w=DEFAULT_ROUTING_SCORE_WEIGHTS;return c.qualityScore*w.quality+c.costScore*w.cost+c.latencyScore*w.latency+c.healthPreference*w.healthPreference;}
  private rejected(provider:ProviderDeclaration,reason:RoutingRejectionReason,phase:EligibilityPhase):RoutingCandidate{return{provider,eligible:false,rejectionReason:reason,rejectionPhase:phase};}
  async findDecisionById(organizationId:string,decisionId:string){return this.prisma.providerRoutingDecision.findFirst({where:{id:decisionId,organizationId},include:{selectedProvider:true}});}
  async findDecisionsByCorrelationId(organizationId:string,correlationId:string){return this.prisma.providerRoutingDecision.findMany({where:{organizationId,correlationId},orderBy:{createdAt:'asc'},include:{selectedProvider:true}});}
  async findDecisionsByWorkflowRunId(organizationId:string,workflowRunId:string){return this.prisma.providerRoutingDecision.findMany({where:{organizationId,workflowRunId},orderBy:{createdAt:'asc'},include:{selectedProvider:true}});}
}
