import { ProviderHealthStatus, ProviderQuotaStatus, ProviderType } from '@vito/contracts';
import { ProviderReadinessProbeService } from './provider-readiness-probe.service';

const provider=(overrides:Record<string,unknown>={})=>({id:'provider-1',organizationId:'org-1',providerCode:'cloud.test',displayName:'Cloud Test',providerType:ProviderType.CLOUD_LLM,status:'ACTIVE',supportedCapabilities:['CODE_BUILD'],capabilityAssignments:[{capabilityCode:'CODE_BUILD',isEnabled:true}],estimatedCostMinorUnits:0,healthStatus:ProviderHealthStatus.HEALTHY,healthCheckedAt:new Date(0),quotaStatus:ProviderQuotaStatus.EXHAUSTED,quotaCheckedAt:new Date(0),qualityScore:1,latencyScore:1,costScore:0,costMetadata:{},assuranceLevels:['AL3'],metadata:{},credentialRequirement:'REQUIRED',createdAt:new Date(),updatedAt:new Date(),...overrides} as any);

describe('ProviderReadinessProbeService',()=>{
  function build(workerResult?:any){const worker={executeSandboxed:jest.fn().mockResolvedValue(workerResult)} as any;const profiles={resolve:jest.fn().mockReturnValue({profileId:'profile-1',providerCode:'cloud.test',credentialRef:'cloud:test',trustedLauncherAlias:'builder',readinessProbeLauncherAlias:'probe',expectedProviderId:'test-provider',allowedModelIds:['model-a'],maxDurationMs:60000,maxParallelism:1,enabled:true})} as any;const trusted={resolve:jest.fn().mockResolvedValue({commandName:'probe',resolvedPath:'/trusted/probe',verifiedAt:new Date()})} as any;const runtime={needsRefresh:jest.fn().mockReturnValue(true),recordProbe:jest.fn().mockResolvedValue(undefined)} as any;return{service:new ProviderReadinessProbeService(worker,profiles,trusted,runtime),worker,profiles,trusted,runtime};}
  it('turns a clean identity-verified probe into fresh AVAILABLE state',async()=>{const{service,runtime}=build({exitCode:0,stdout:'VITO_PROVIDER_READY',stderr:'providerID=test-provider modelID=model-a',durationMs:321,timedOut:false,oomKilled:false,baseSha:'abc',repositoryId:'lavolpeofficial/vito-platform',workspaceDisposition:'CLEANED',governedResultSettling:{executionId:'e1',baseSha:'abc',changedFiles:[],patch:'',empty:true},observedProviderIdentity:{providerId:'test-provider',modelId:'model-a'}});const result=await service.refreshIfStale({organizationId:'org-1',provider:provider()});expect(result.refreshed).toBe(true);expect(runtime.recordProbe).toHaveBeenCalledWith('org-1','provider-1',expect.objectContaining({healthStatus:ProviderHealthStatus.HEALTHY,quotaStatus:ProviderQuotaStatus.AVAILABLE,reasonCode:'PROBE_SUCCEEDED'}));});
  it('records usage-limit evidence as EXHAUSTED instead of fabricating availability',async()=>{const{service,runtime}=build({exitCode:1,stdout:'',stderr:'provider.rate-limit: The usage limit has been reached',durationMs:222,timedOut:false,oomKilled:false,baseSha:'abc',repositoryId:'lavolpeofficial/vito-platform',workspaceDisposition:'CLEANED',governedResultSettling:{executionId:'e2',baseSha:'abc',changedFiles:[],patch:'',empty:true},observedProviderIdentity:{providerId:'test-provider',modelId:'model-a'}});await service.refreshIfStale({organizationId:'org-1',provider:provider()});expect(runtime.recordProbe).toHaveBeenCalledWith('org-1','provider-1',expect.objectContaining({quotaStatus:ProviderQuotaStatus.EXHAUSTED,reasonCode:'PROBE_QUOTA_EXHAUSTED'}));});
  it('fails closed without a server-owned probe launcher and does not execute',async()=>{const{service,profiles,worker,runtime}=build();profiles.resolve.mockReturnValue({profileId:'profile-1',providerCode:'cloud.test',credentialRef:'cloud:test',trustedLauncherAlias:'builder',expectedProviderId:'test-provider',maxDurationMs:60000,maxParallelism:1,enabled:true});const result=await service.refreshIfStale({organizationId:'org-1',provider:provider()});expect(result).toEqual(expect.objectContaining({attempted:false,refreshed:false,reasonCode:'PROBE_PROFILE_UNAVAILABLE'}));expect(worker.executeSandboxed).not.toHaveBeenCalled();expect(runtime.recordProbe).not.toHaveBeenCalled();});
});
