export type WorkforceCapability = Readonly<{ id:string; code:string; name:string; riskLevel:string; requiresApproval:boolean }>;
export type WorkforceEmployee = Readonly<{ id:string; name:string; code:string; employeeType:string; status:string; version:string; workforceInstanceId:string|null; capabilities: readonly Readonly<{ isEnabled:boolean; capability: WorkforceCapability }>[] }>;
export type ProviderSnapshot = Readonly<{ authority:'READ_ONLY'; providers: readonly Readonly<{ id:string; providerCode:string; displayName:string; status:string; healthStatus:string; quotaStatus:string; staticallyRoutable:boolean; enabledCapabilities: readonly string[] }>[]; capabilityCoverage: readonly Readonly<{ capabilityCode:string; enabledProviderCount:number; staticallyRoutableProviderCount:number; providerCodes:readonly string[]; readiness:string }>[] }>;
export type CapabilityDiscovery = Readonly<{ code:string; availability:string; officialEngineeringCapability:boolean; assignedDigitalEmployeeCount:number; registeredCapability: null | Readonly<{ id:string; name:string; riskLevel:string; requiresApproval:boolean }>; executableProviders: readonly Readonly<{ providerId:string; providerCode:string; healthStatus:string; quotaStatus:string }>[]; gap:null|Readonly<{ type:string; suggestedNextState:string }> }>;

export function parseEmployees(input:unknown): readonly WorkforceEmployee[] | null {
 if(!Array.isArray(input)||input.length>500) return null; const out:WorkforceEmployee[]=[];
 for(const item of input){const r=rec(item); if(!r||!str(r.id)||!str(r.name)||!str(r.code)||!str(r.employeeType)||!str(r.status)||!str(r.version)||!nullableStr(r.workforceInstanceId)||!Array.isArray(r.capabilities)||r.capabilities.length>200)return null; const caps=[] as {isEnabled:boolean;capability:WorkforceCapability}[]; for(const a of r.capabilities){const ar=rec(a), c=rec(ar?.capability); if(!ar||typeof ar.isEnabled!=='boolean'||!c||!str(c.id)||!str(c.code)||!str(c.name)||!str(c.riskLevel)||typeof c.requiresApproval!=='boolean')return null; caps.push({isEnabled:ar.isEnabled,capability:{id:c.id,code:c.code,name:c.name,riskLevel:c.riskLevel,requiresApproval:c.requiresApproval}});} out.push({id:r.id,name:r.name,code:r.code,employeeType:r.employeeType,status:r.status,version:r.version,workforceInstanceId:r.workforceInstanceId,capabilities:caps}); }
 return out;
}
export function parseCapabilities(input:unknown): readonly WorkforceCapability[] | null { if(!Array.isArray(input)||input.length>500)return null; const out:WorkforceCapability[]=[]; for(const item of input){const r=rec(item); if(!r||!str(r.id)||!str(r.code)||!str(r.name)||!str(r.riskLevel)||typeof r.requiresApproval!=='boolean')return null; out.push({id:r.id,code:r.code,name:r.name,riskLevel:r.riskLevel,requiresApproval:r.requiresApproval});} return out; }
export function parseProviderSnapshot(input:unknown):ProviderSnapshot|null { const r=rec(input); if(!r||r.authority!=='READ_ONLY'||!Array.isArray(r.providers)||!Array.isArray(r.capabilityCoverage)||r.providers.length>100||r.capabilityCoverage.length>500)return null; const providers=[] as ProviderSnapshot['providers'][number][]; for(const p0 of r.providers){const p=rec(p0); if(!p||!str(p.id)||!str(p.providerCode)||!str(p.displayName)||!str(p.status)||!str(p.healthStatus)||!str(p.quotaStatus)||typeof p.staticallyRoutable!=='boolean'||!strArray(p.enabledCapabilities))return null; providers.push({id:p.id,providerCode:p.providerCode,displayName:p.displayName,status:p.status,healthStatus:p.healthStatus,quotaStatus:p.quotaStatus,staticallyRoutable:p.staticallyRoutable,enabledCapabilities:p.enabledCapabilities});} const coverage=[] as ProviderSnapshot['capabilityCoverage'][number][]; for(const c0 of r.capabilityCoverage){const c=rec(c0); if(!c||!str(c.capabilityCode)||!num(c.enabledProviderCount)||!num(c.staticallyRoutableProviderCount)||!strArray(c.providerCodes)||!str(c.readiness))return null; coverage.push({capabilityCode:c.capabilityCode,enabledProviderCount:c.enabledProviderCount,staticallyRoutableProviderCount:c.staticallyRoutableProviderCount,providerCodes:c.providerCodes,readiness:c.readiness});} return {authority:'READ_ONLY',providers,capabilityCoverage:coverage}; }
export function parseCapabilityDiscovery(input:unknown):CapabilityDiscovery|null { const r=rec(input), reg=rec(r?.registeredCapability), gap=rec(r?.gap); if(!r||!str(r.code)||!str(r.availability)||typeof r.officialEngineeringCapability!=='boolean'||!num(r.assignedDigitalEmployeeCount)||!Array.isArray(r.executableProviders)||r.executableProviders.length>100)return null; if(r.registeredCapability!==null&&(!reg||!str(reg.id)||!str(reg.name)||!str(reg.riskLevel)||typeof reg.requiresApproval!=='boolean'))return null; const ps=[] as CapabilityDiscovery['executableProviders'][number][]; for(const p0 of r.executableProviders){const p=rec(p0); if(!p||!str(p.providerId)||!str(p.providerCode)||!str(p.healthStatus)||!str(p.quotaStatus))return null; ps.push({providerId:p.providerId,providerCode:p.providerCode,healthStatus:p.healthStatus,quotaStatus:p.quotaStatus});} if(r.gap!==null&&(!gap||!str(gap.type)||!str(gap.suggestedNextState)))return null; return {code:r.code,availability:r.availability,officialEngineeringCapability:r.officialEngineeringCapability,assignedDigitalEmployeeCount:r.assignedDigitalEmployeeCount,registeredCapability:r.registeredCapability===null?null:{id:reg!.id as string,name:reg!.name as string,riskLevel:reg!.riskLevel as string,requiresApproval:reg!.requiresApproval as boolean},executableProviders:ps,gap:r.gap===null?null:{type:gap!.type as string,suggestedNextState:gap!.suggestedNextState as string}}; }
function rec(v:unknown):Record<string,unknown>|null{return typeof v==='object'&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:null} function str(v:unknown):v is string{return typeof v==='string'&&v.length>0&&v.length<=512} function nullableStr(v:unknown):v is string|null{return v===null||str(v)} function num(v:unknown):v is number{return typeof v==='number'&&Number.isSafeInteger(v)&&v>=0} function strArray(v:unknown):v is string[]{return Array.isArray(v)&&v.length<=500&&v.every(str)}
